### ISSUE TITLE
pcaExplorer - locally installed shiny app issue 

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/pcaExplorer#13]
Hi @federicomarini 

I could not see any issues posted on https://github.com/federicomarini/pcaExplorer_serveredition - I however posted one there
https://github.com/federicomarini/pcaExplorer_serveredition/issues/1

I did not know if this is the place to post issues related to pcaExplorer shiny app related issues.

Thanks

**Comment by federicomarini** [comment]
Either is fine, I am keeping all of them under control 😉 
I'll try to answer that there directly!
