### ISSUE TITLE
Can't see the genes name

### ISSUE THREAD

**Issue by nancyruizu** [federicomarini/pcaExplorer#18]
Hi Dr. Marini,

Your shiny app is one of the best tools I've seen out there for us, beginners in the field of bioinformatics, to look at differentially expressed gene data. For that, I would like to thank you for building it and making it open source and accessible. 
Everything runs smoothly for me, except that I can't see the gene names in the dot plots, similar to an issue someone had back in 2020. Attached you'll find my sample counts, metadata, and annotation. Not sure what I'm doing wrong. My annotation file is a tab-delimited .txt file with two columns, gene_id (ENSMUG) and gene_name. 

Thanks so much for your help,

Best

Nancy

![Screen Shot 2022-05-18 at 4 47 03 PM](https://user-images.githubusercontent.com/64565207/169153314-58976924-a2a7-43cf-851d-10821cbfb3d3.png)
![Screen Shot 2022-05-18 at 4 46 48 PM](https://user-images.githubusercontent.com/64565207/169153316-3461f58c-0923-4c07-b59c-63dbdc00a5a3.png)
![Screen Shot 2022-05-18 at 4 46 37 PM](https://user-images.githubusercontent.com/64565207/169153317-079bc789-98f6-4cfa-a2e3-7a69efadae7d.png)

**Comment by federicomarini** [comment]
Hi Nancy, 
thanks for the kind words!

My first guess is that the annotation file is not as expected.
To fix that quickly:
* try setting the row names to the values of the gene ids
* try renaming the first column to `gene_id`

I guess that could make it possible to recognize the column to pick the gene name from.

HTH,
Federico

**Comment by nancyruizu** [comment]
Hi Federico,

Setting the row names to the value of the gene ids fixed it.

Thanks for your help,


Nancy

**Comment by federicomarini** [comment]
Thank you for the feedback!
Closing this one 😉
