### ISSUE TITLE
threeJs update stops pcaExplorer working 

### ISSUE THREAD

**Issue by ReubenMcG** [federicomarini/pcaExplorer#2]
Hi, 

I was plotting 3D PCA's from Desq2 output using simple:

> pcaplot3d(ddsMF, intgroup = "donor")

I then updated some packages:

> install.packages(c("httr", "Matrix", "plotrix", "shape", "shiny", "threejs", "tidyr"))

And then the pcaplot3D function returns this error:

Error in scatterplot3js(d[, 1:3], color = cols, renderer = "canvas", size = 1.3,  : 
  (list) object cannot be coerced to type 'double'

I installed the older version of threeJs:

> require(devtools)

> install_version("threejs", version = "0.2.2", repos = "http://cran.us.r-project.org")

And then plot3dpca runs fine again,

Thanks,

Reuben

**Comment by federicomarini** [comment]
I'll try to reproduce your error if you provide me with the sessionInfo outputs.
As of now seems the issue is resolved?
Cheers,
Federico

**Comment by ReubenMcG** [comment]
Hi Federico

> R version 3.4.1 (2017-06-30)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Sierra 10.12.6
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] pcaExplorer_2.2.0          plotly_4.7.1               ggplot2_2.2.1              DESeq2_1.16.1             
>  [5] SummarizedExperiment_1.6.3 DelayedArray_0.2.7         matrixStats_0.52.2         Biobase_2.36.2            
>  [9] GenomicRanges_1.28.4       GenomeInfoDb_1.12.2        IRanges_2.10.2             S4Vectors_0.14.3          
> [13] BiocGenerics_0.22.0       
> 
> loaded via a namespace (and not attached):
>   [1] colorspace_1.3-2        rprojroot_1.2           htmlTable_1.9           XVector_0.16.0         
>   [5] base64enc_0.1-3         d3heatmap_0.6.1.1       topGO_2.28.0            ggrepel_0.6.5          
>   [9] DT_0.2                  bit64_0.9-7             AnnotationDbi_1.38.2    codetools_0.2-15       
>  [13] splines_3.4.1           doParallel_1.0.10       geneplotter_1.54.0      knitr_1.17             
>  [17] Formula_1.2-2           jsonlite_1.5            gridBase_0.4-7          annotate_1.54.0        
>  [21] cluster_2.0.6           GO.db_3.4.1             png_0.1-7               pheatmap_1.0.8         
>  [25] shinydashboard_0.6.1    graph_1.54.0            shiny_1.0.4             compiler_3.4.1         
>  [29] httr_1.3.0              GOstats_2.42.0          backports_1.1.0         assertthat_0.2.0       
>  [33] Matrix_1.2-11           lazyeval_0.2.0          limma_3.32.5            acepack_1.4.1          
>  [37] htmltools_0.3.6         tools_3.4.1             bindrcpp_0.2            Category_2.42.1        
>  [41] gtable_0.2.0            glue_1.1.1              GenomeInfoDbData_0.99.0 reshape2_1.4.2         
>  [45] dplyr_0.7.2             Rcpp_0.12.12            NMF_0.20.6              iterators_1.0.8        
>  [49] crosstalk_1.0.0         stringr_1.2.0           mime_0.5                rngtools_1.2.4         
>  [53] XML_3.98-1.9            shinyAce_0.2.1          zlibbioc_1.22.0         scales_0.4.1.9002      
>  [57] shinyBS_0.61            RBGL_1.52.0             SparseM_1.77            RColorBrewer_1.1-2     
>  [61] yaml_2.1.14             memoise_1.1.0           gridExtra_2.2.1         pkgmaker_0.22          
>  [65] biomaRt_2.32.1          rpart_4.1-11            latticeExtra_0.6-28     stringi_1.1.5          
>  [69] RSQLite_2.0             genefilter_1.58.1       foreach_1.4.3           checkmate_1.8.3        
>  [73] BiocParallel_1.10.1     rlang_0.1.2             pkgconfig_2.0.1         bitops_1.0-6           
>  [77] evaluate_0.10.1         lattice_0.20-35         purrr_0.2.3             bindr_0.1              
>  [81] htmlwidgets_0.9         bit_1.1-12              AnnotationForge_1.18.1  GSEABase_1.38.0        
>  [85] plyr_1.8.4              magrittr_1.5            R6_2.2.2                Hmisc_4.0-3            
>  [89] DBI_0.7                 foreign_0.8-69          survival_2.41-3         RCurl_1.95-4.8         
>  [93] nnet_7.3-12             tibble_1.3.3            rmarkdown_1.6           locfit_1.5-9.1         
>  [97] grid_3.4.1              data.table_1.10.4       blob_1.1.0              threejs_0.3.1          
> [101] digest_0.6.12           xtable_1.8-2            tidyr_0.7.0             httpuv_1.3.5           
> [105] munsell_0.4.3           registry_0.3            viridisLite_0.2.0 :
> 

This is resolved for now by installing legacy threejs_0.2.2

Thank you,

Reuben

**Comment by federicomarini** [comment]
For the sake of completion:

issue solved in commit https://github.com/federicomarini/pcaExplorer/commit/95422a244a183329bbd183785e3fef4be5d1ebe4
