### ISSUE TITLE
pcaExplorer on PCA from Seurat

### ISSUE THREAD

**Issue by lucygarner** [federicomarini/pcaExplorer#20]
Hi,

Is there a way to use pcaExplorer with the DimReduc object from Seurat (i.e. convert this into a suitable format)? Or would I need to run `prcomp`?

Best wishes,
Lucy

**Comment by federicomarini** [comment]
Hi Lucy,
Using directly the `SeuratObject` is not possible at the moment.
A workaround: convert that object to a SummarizedExperiment/SingleCellExperiment, and then use those results as input?
Considering that the development of pcaExplorer started way before Seurat (and single cell data 😛 ), it might mean quite a large piece of work to refactor/allow that input.
Sorry I do not have a better answer!
Federico

**Comment by lucygarner** [comment]
Thanks @federicomarini. No worries, I just wanted to check. I was looking at the `hi_loadings` function but it says the input is a `prcomp` object. Can you also supply a `SingleCellExperiment` object?

I have currently written my own version of the function that extracts the loadings from a Seurat object instead.

**Comment by federicomarini** [comment]
Hm, same as for `pcaExplorer()` - that works on a DESeqDataSet mainly, so all things use to be computed at runtime (which was never a large deal with the "classical" small bulk RNA-seq datasets...).
Probably you are best served if you stick to the Seurat framework, I have the impression it might cover a few things you would do with pcaExplorer - well, of course, not in the context of a nicely designed app 😉

**Comment by lucygarner** [comment]
Yes, datasets are a bit larger now! Thanks for the quick response.
