### ISSUE TITLE
Deplying pcaExplorer as shinyApp on a shiny server

### ISSUE THREAD

**Issue by danielmart** [federicomarini/pcaExplorer#4]
Hi Federico,
First of all, thank you very much for your wonderful work. We are looking into deploying your tool as a pure shinyApp in a production shiny server in our institution (already working and serving other apps). I know launching pcaExplorer() from RStudio is easy enough, but this is meant for end users who are not familiar with R whatsoever, and even installing RStudio locally to their machines is a hurdle. Is there an easy way to achieve this?

**Comment by federicomarini** [comment]
Hi Daniel,

would this here (https://github.com/federicomarini/pcaExplorer_serveredition) do the job for you?

Cheers,
Federico

**Comment by danielmart** [comment]
Ha! Was that there the whole time? I feel really stupid now...
Thanks a lot, will give it a shot. Keep up the good work.

**Comment by federicomarini** [comment]
No need to feel stupid, good thing you found it now 😄 
Thank you for the nice words!
Federico

**Comment by federicomarini** [comment]
Catching up on the open issue, I'd close this one 😉
