### ISSUE TITLE
Request: add FDR and permit any of topGO's statistical tests

### ISSUE THREAD

**Issue by tantrev** [federicomarini/pcaExplorer#5]
Hello!  I've really been enjoying using pcaExplorer, especially its pca2go function.  I've noticed that pca2go uses the classic and elim p-values from topGO - it would just be nice if the user could specify any of the algorithm's offered by topGO.  The addition of a false discovery rate correction inside pcaExplorer would also be really great.

**Comment by federicomarini** [comment]
Hi Trevor,
that's definitely a reasonable point. I always had good experiences especially with `elim`, but I can try to expose that as a parameter.

As for the FDR, I am little more torn: the Gene Ontology terms are not really independent between each others, due to their inherent DAG structure. 
Then one of the assumptions for the multiple testing adjustment seems to kinda melt down.
Given the fact one always has to take these results with more and more grains of salt... I can think of putting an optional switch for correction.

**Comment by tantrev** [comment]
Hi Federico,
Thank you for the quick and kind reply!  I'm pretty new to the intricacies of gene enrichment and appreciate your explanations on things.

Looking at topGO's manual, I had just noticed that the default test (weight01) was different than the two currently used in pcaExplorer.  You have a good point about independence and FDR as well - I was just wondering because it seemed that at least [one publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732277/) - for better or worse - had bolted FDR onto their gene enrichment analysis.

Thanks again.

**Comment by federicomarini** [comment]
In my experience I had a good result with the combination of `classic` and `elim` for pruning down un-informative categories.

I'd proceed with the following:
- a parameter to choose the additional topGO method, with `classic` being done by default, and p values returned sorted on this specific topGO method
- adjustment p values with a logical that uses `p.adjust`, of course before subsetting the table.

I'll follow up on this once the related commits are in

**Comment by federicomarini** [comment]
Choice of extra topGO methods is implemented here: https://github.com/federicomarini/pcaExplorer/commit/bdd65e6424a9cb184a6ed10283ec52e40a57c117

**Comment by federicomarini** [comment]
... and here is the commit implementing the option to adjust directly the topGO p-values: https://github.com/federicomarini/pcaExplorer/commit/55879a91d568d565e90c6bcd9ea0b31402d07370

To get a version where these are in, install the version from either the Devel branch in Bioc (3.9) or directly here from GitHub ;)

**Comment by tantrev** [comment]
You're amazing Federico, thank you so much!  I really appreciate it.

**Comment by federicomarini** [comment]
Glad I could help, thank you for the kind words ☺️

**Comment by tantrev** [comment]
So you're going to hate me, but it may be worth considering making "BY" the default method for adjusting p-values instead of "BH" because of its supposed validity in some cases of dependence:
https://stats.stackexchange.com/questions/205516/fdr-correction-when-tests-are-correlated
Anyways, just a thought.  :) Thanks again.

**Comment by tantrev** [comment]
Forgive me, my final thought is just that it may be nice for pca2go to return the "probesPC1pos", etc. values.  Since topGO seems to only look at "biological process" annotations from GO, such functionality would enable the use of other tools to assess other ontology categories like "molecular function" and "cellular component"

**Comment by federicomarini** [comment]
> So you're going to hate me, but it may be worth considering making "BY" the default method for adjusting p-values instead of "BH" because of its supposed validity in some cases of dependence

no need for hate 😄, I'll switch to that

**Comment by federicomarini** [comment]
> it may be nice for pca2go to return the "probesPC1pos", etc. values

I can have a list returned early with the content of these vectors.

**Comment by federicomarini** [comment]
BY instead of BH: https://github.com/federicomarini/pcaExplorer/commit/599175380cd812d9cd6b804bf98904634e7b2e84

Returning a list from `pca2go`, via `return_ranked_gene_loadings`: https://github.com/federicomarini/pcaExplorer/commit/2d7c4ba292cad92757cead773e08467ca3025e5e
