### ISSUE TITLE
pcaExplorer not displaying properly

### ISSUE THREAD

**Issue by jmickey** [federicomarini/pcaExplorer#6]
Version:

- R: 3.6.1
- Rstudio: 1.1.447
- pcaExplorer: 2.11.2
- Shiny: 1.3.2
- DESeq2: 1.24.0

When loading pcaExplorer (with a `dds` value), I get the following screen:

![image](https://user-images.githubusercontent.com/7720995/61572783-d9f66580-aa9a-11e9-99c0-c4c34a9905d5.png)

No data is loaded, the `airway` dataset (installed) also won't load. Even the help button to the right of the 'load demo airway data' does nothing when clicked.

Also had this issue with all the above packages running on R 3.5.2.

**Comment by federicomarini** [comment]
Hi Josh,
sorry for the inconvenience.
I'm traveling these days and will be back in a couple of weeks.

Can you obtain the same error if you use a release version (say, 2.10.0)?
Thing is, I did use the package recently for a demo and did not encounter such a "showstopper". And I did not change the code so massively to think it is because of this package - maybe some of the dependencies have done some changes, I'll look into that soon!

Thanks for reporting this
Federico

**Comment by federicomarini** [comment]
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/7447478/61575666-c49b2e80-aace-11e9-8b13-d63e3b86ecda.png">

I checked the public instance we are running at http://shiny.imbei.uni-mainz.de:3838/pcaExplorer/ and this works - albeit with the older Bioc release.
I'll follow up on this once updated to Bioc 3.9

**Comment by jmickey** [comment]
[Whoops, didn't mean to close]

Hi Federico,

Thanks for the reply! 

I get the same issue with the latest stable release installed via BiocManager. I only installed the latest from GitHub when the stable release didn't work.

Regards,
Josh

**Comment by jmickey** [comment]
@federicomarini Interestingly - the public instance (http://shiny.imbei.uni-mainz.de:3838/pcaExplorer) is also showing the same behaviour for me.

**Comment by federicomarini** [comment]
> @federicomarini Interestingly - the public instance (http://shiny.imbei.uni-mainz.de:3838/pcaExplorer) is also showing the same behaviour for me.

That is happening after I updated to the latest release.
I'll have to investigate that deeper but that needs to wait a little time - apologies for the inconvenience again

**Comment by pzumbo** [comment]
Problem may be with shinyAce v0.4.0, which pcaExplorer imports.  Downgrading to shinyAce_0.3.2 fixed the problem for me.  ShinyAce release notes mention "breaking" changes (https://cran.r-project.org/web/packages/shinyAce/news/news.html).

**Comment by federicomarini** [comment]
> Problem may be with shinyAce v0.4.0, which pcaExplorer imports. Downgrading to shinyAce_0.3.2 fixed the problem for me. ShinyAce release notes mention "breaking" changes (https://cran.r-project.org/web/packages/shinyAce/news/news.html).

Excellent catch @pzumbo. I did see the new release but did not think it would have affected so massively the apps (`pcaExplorer`, but also `ideal`).
I'll leave the issue open for the time being, since I can not really actively work on a fix, I'll check in depth once I'm back.

But again: thanks!

**Comment by josiegleeson** [comment]
Hi Federico,

I am having the same issue as Josh, I believe it is the shinyAce that is stopping it from working but I cannot downgrade my version as the old one says it is not compatible with R 3.6 

Thanks for your quick reply to my email, even though you're away at the moment!

Hopefully some time soon there will be a solution to this, thanks.

![Screen Shot 2019-08-01 at 12 27 17 pm](https://user-images.githubusercontent.com/30969357/62268465-531a9300-b473-11e9-8ca9-7a544e508496.png)
![Screen Shot 2019-08-01 at 12 29 57 pm](https://user-images.githubusercontent.com/30969357/62268487-5b72ce00-b473-11e9-88ed-deb38be3e3ef.png)

**Comment by federicomarini** [comment]
Seems to be solved now.
Would be amazing if @pzumbo @josiegleeson and|or @jaymickey could give me a quick feedback it is solved on their side as well 😌, then I would close this one

**Comment by sridewi1** [comment]
Hi,
I am also facing the same issue. I am also not able to downgrade shinyAce. So I hope to hear more, if there is any solution to solve this. Thanks in advance! :)

**Comment by federicomarini** [comment]
Hi Sri,
it should be solved now if you install either release, devel, or the GitHub devel from here.
Federico

**Comment by sridewi1** [comment]
@federicomarini it did! Thanks a lot and nice tool, btw! :) 
and one tip, the colour of the text (deep gray) is quite hard to see due to the dark background colour (deep blue). So it will be nice if the colour of the text could be a little ligther than the background colour. Thanks!

**Comment by federicomarini** [comment]
> @federicomarini it did! Thanks a lot and nice tool, btw! :)

Thanks for both, feedback re: bug and re: tool in general!

> and one tip, the colour of the text (deep gray) is quite hard to see due to the dark background colour (deep blue). So it will be nice if the colour of the text could be a little ligther than the background colour. Thanks!

Do you mean for the buttons? I can try and see what I can do css-wise maybe ;)

**Comment by federicomarini** [comment]
Closing this one as it seems to be resolved, thanks once again @sridewi1!

**Comment by jmickey** [comment]
Thanks folks! Seems to be all good on this end too.
