### ISSUE TITLE
pcaExplorer under R 3.6.1

### ISSUE THREAD

**Issue by Drepanis** [federicomarini/pcaExplorer#8]
pcaExplorer is awesome!

Error: dev.control() called without an open graphics device

I am attempting to run pcaExplorer under R 3.6.1 and I am getting an error when downloading the Rmd generate and save button. Basically, R 3.6.1 is not compatible with the grdevices. It is suggested that I edit code from pdf(file) to pdf(file=NULL). 

I scanned the documentation and didn't see what the maximum supported version of R is (ok, probably the last one supporting grdevices).

Can you suggest a workaround for pcaExplorer under R 3.6.1?

Thank you.

**Comment by federicomarini** [comment]
Hi @Drepanis ,

my current devel setup is with R-3.6.0 and I did not encounter any issue to date.

Regarding the issue, still: once you download and save the report, it actually saves a HTML file. Plus I did search around for the `grDevices` compatibility, but I could not find much about a possible solution.

Can you provide me with some clearer sessionInfo + conditions where the error is triggered?

Let me investigate a bit more and I'll be back to you!
Federico

**Comment by federicomarini** [comment]
closing for long time inactivity 😉
