### ISSUE TITLE
Error Importing data

### ISSUE THREAD

**Issue by LGray95** [federicomarini/pcaExplorer#9]
Hi there!

I'm very excited to use pcaExplorer but I am having some difficulty in reading in the files. I receive the error:

"Warning: Error in DESeqDataSet: some values in assay are not integers
  [No stack trace available]"

But running the sample data works fine.

I believe that the format of my files is correct, but I could be mistaken in this.

Thank you in advance for your help!

**Comment by federicomarini** [comment]
Hi @LGray95 !

Super happy about the excitement, but less about the error.

The reason - possibly: are you uploading something else than the (raw) count matrix? 

Federico

**Comment by federicomarini** [comment]
closing for long time inactivity 😉
